---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "ui.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.allow-http: "false"
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managemt-by: {{ .Release.Service }}
spec:
  ingressClassName: nginx
  rules:
#    - host: reddit.infranet.dev
    - http:
        paths:
          - pathType: ImplementationSpecific
            path: /
            backend:
              service:
                name: {{ template "ui.fullname" . }}
                port:
                  number: {{ .Values.service.externalPort }}
