---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  annotations:
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
    - http:
        paths:
          - pathType: ImplementationSpecific
            path: /*
            backend:
              serviceName: {{ .Release.Name }}-{{ .Chart.Name }}
              servicePort: 9292
