version: '3.3'
services:

  post_db:
    image: mongo:${MONGO_VERSION}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - comment_db

  ui:
    env_file:
      - .env
    image: ${USER_NAME}/ui:${UI_VERSION}
    ports:
      - ${PORT}:${PORT}/tcp
    networks:
      - front_net
      - prometheus_net

  post:
    env_file:
      - .env
    image: ${USER_NAME}/post:${POST_VERSION}
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post
    networks:
      - back_net
      - front_net
      - prometheus_net

  comment:
    env_file:
      - .env
    image: ${USER_NAME}/comment:${COMMENT_VERSION}
    networks:
      - back_net
      - front_net
      - prometheus_net

  prometheus:
    image: ${USER_NAME}/prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command: # Передаем доп параметры в командной строке
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d' # Задаем время хранения метрик в 1 день
    networks:
      - prometheus_net

  node-exporter:
    image: prom/node-exporter:v0.15.2
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      - prometheus_net

  mongodb_exporter:
    image: percona/mongodb_exporter:0.39
    command:
      - '--mongodb.uri=mongodb://post_db:27017'
      - '--mongodb.collstats-colls=users_post.posts,comments.comments'
      - '--log.level=debug'
      - '--collector.collstats'
#      - '--collect-all'
    networks:
      - back_net
      - prometheus_net

  blackbox_exporter:
    image: prom/blackbox-exporter:v0.24.0
    ports:
      - '9115:9115'
    networks:
      - prometheus_net

volumes:
  post_db:
  prometheus_data:

networks:
  back_net:
  front_net:
  prometheus_net:
