version: '3.3'
services:
  post_db:
    image: mongo:${MONGO_VERSION}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - comment_db
  ui:
    env_file:
      - .env
#    build: ./ui
    image: ${USER_NAME}/ui:${UI_VERSION}
    ports:
      - ${PORT}:${PORT}/tcp
    networks:
      - front_net

  post:
    env_file:
      - .env
#    build: ./post-py
    image: ${USER_NAME}/post:${POST_VERSION}
    networks:
      - back_net
      - front_net

  comment:
    env_file:
      - .env
#    build: ./comment
    image: ${USER_NAME}/comment:${COMMENT_VERSION}
    networks:
      - back_net
      - front_net

  prometheus:
    image: ${USER_NAME}/prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command: # Передаем доп параметры в командной строке
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d' # Задаем время хранения метрик в 1 день
    networks:
      - prometheus_net

volumes:
  post_db:
  prometheus_data:

networks:
  back_net:
  front_net:
  prometheus_net:
