---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc-dynamic
  labels:
    app: reddit
    component: pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi